import { useState, useRef, useCallback } from "react";
import { createWSConnection, wsSend } from "../services/websocket.js";

export function useRunner() {
  const [wsStatus, setWsStatus]           = useState("disconnected");
  const [runLog, setRunLog]               = useState([]);
  const [runPhase, setRunPhase]           = useState("idle");
  const [steps, setSteps]                 = useState([]);
  const [currentStep, setCurrentStep]     = useState(-1);
  const [screenshots, setScreenshots]     = useState([]);
  const [viewShot, setViewShot]           = useState(null);
  const [assertions, setAssertions]       = useState([]);
  const [suiteProgress, setSuiteProgress] = useState(null);
  const [runTarget, setRunTarget]         = useState(null);

  const wsRef    = useRef(null);
  const runLogRef = useRef(null);

  const addRunLog = useCallback((msg, level = "info") => {
    setRunLog(prev => [...prev, { msg, level }]);
    setTimeout(() => runLogRef.current?.scrollTo({ top: 99999, behavior: "smooth" }), 50);
  }, []);

  const handleMessage = useCallback((msg) => {
    switch (msg.type) {
      case "connected":
        addRunLog("Backend connected ✓", "success"); break;

      case "run_start":
        setRunPhase("running"); setSteps([]); setAssertions([]);
        setScreenshots([]); setCurrentStep(-1); setRunTarget(msg);
        addRunLog(`Starting: ${msg.title}`, "system"); break;

      case "log":
        addRunLog(msg.msg, msg.level); break;

      case "actions_ready":
        addRunLog(`${msg.count} actions generated by AI`, "ai");
        setSteps(Array(msg.count).fill(null).map((_, i) => ({ index: i, status: "pending", description: "" }))); break;

      case "step_start":
        setCurrentStep(msg.index);
        setSteps(prev => prev.map((s, i) =>
          i === msg.index ? { ...s, status: "running", description: msg.description } : s
        ));
        addRunLog(`Step ${msg.index + 1}/${msg.total}: ${msg.description}`, "action"); break;

      case "step_done":
        setSteps(prev => prev.map((s, i) =>
          i === msg.index ? { ...s, status: msg.status, screenshot: msg.screenshot, error: msg.error, description: msg.description } : s
        ));
        if (msg.screenshot) setScreenshots(prev => [...prev, { data: msg.screenshot, label: msg.description, status: msg.status }]);
        addRunLog(msg.status === "fail" ? `✗ ${msg.error}` : `✓ ${msg.description}`, msg.status === "fail" ? "error" : "success"); break;

      case "screenshot":
        if (msg.data) setScreenshots(prev => [...prev, { data: msg.data, label: msg.step, status: "info" }]); break;

      case "assertion":
        setAssertions(prev => [...prev, msg]);
        addRunLog(`${msg.passed ? "✓" : "✗"} Assert: ${msg.assertion}`, msg.passed ? "success" : "warn"); break;

      case "run_complete":
        setRunPhase("done");
        addRunLog(`Run complete — ${msg.passed} passed, ${msg.failed} failed`, msg.failed === 0 ? "success" : "warn"); break;

      case "run_error":
        setRunPhase("error"); addRunLog(`Error: ${msg.error}`, "error"); break;

      case "suite_start":
        setSuiteProgress({ total: msg.total, done: 0 }); break;

      case "suite_complete":
        setSuiteProgress(prev => prev ? { ...prev, done: msg.ran.length } : null);
        addRunLog(`Suite complete — ${msg.ran.length} use cases ran`, "success"); break;

      case "stopped":
        setRunPhase("idle"); addRunLog("Stopped.", "system"); break;
    }
    setTimeout(() => runLogRef.current?.scrollTo({ top: 99999, behavior: "smooth" }), 50);
  }, [addRunLog]);

  const connect = useCallback(() => {
    if (wsRef.current?.readyState === WebSocket.OPEN) return;
    setWsStatus("connecting");
    wsRef.current = createWSConnection({
      onOpen:    () => setWsStatus("connected"),
      onClose:   () => { setWsStatus("disconnected"); wsRef.current = null; },
      onError:   () => setWsStatus("error"),
      onMessage: handleMessage,
    });
  }, [handleMessage]);

  const send = useCallback((payload) => {
    if (wsRef.current?.readyState === WebSocket.OPEN) {
      wsSend(wsRef.current, payload);
    } else {
      addRunLog("Backend not connected. Start the backend server first.", "error");
    }
  }, [addRunLog]);

  const runUseCase = useCallback((useCase, url, credentials) => {
    send({ type: "run_usecase", useCase, url, credentials });
  }, [send]);

  const runSuite = useCallback((useCases, url, credentials) => {
    send({ type: "run_suite", useCases, url, credentials });
  }, [send]);

  const stopRun = useCallback(() => {
    send({ type: "stop" });
  }, [send]);

  const resetRunner = useCallback(() => {
    setRunLog([]); setSteps([]); setScreenshots([]);
    setAssertions([]); setRunPhase("idle"); setCurrentStep(-1);
    setSuiteProgress(null); setRunTarget(null);
  }, []);

  return {
    wsStatus, connect,
    runLog, runLogRef,
    runPhase, steps, currentStep,
    screenshots, viewShot, setViewShot,
    assertions, suiteProgress, runTarget,
    runUseCase, runSuite, stopRun, resetRunner,
  };
}
