/**
 * Posts ATP test results back to a GitHub PR as:
 * 1. A commit status check (✓ / ✗ on the PR)
 * 2. A detailed PR comment with test results, AI analysis, and recommendations
 */

const GH_API = "https://api.github.com";

/**
 * Post a commit status check to GitHub.
 * Shows as a check on the PR — green tick or red X.
 */
export async function postCommitStatus(prEvent, status, description, token) {
  if (!token) return;

  const state = status === "pass" ? "success"
    : status === "running"        ? "pending"
    : "failure";

  await fetch(`${GH_API}/repos/${prEvent.repoFullName}/statuses/${prEvent.sha}`, {
    method:  "POST",
    headers: {
      Authorization: `Bearer ${token}`,
      Accept:        "application/vnd.github.v3+json",
      "Content-Type": "application/json",
      "User-Agent":  "ATP-Bot",
    },
    body: JSON.stringify({
      state,
      description: description.slice(0, 140),
      context:     "ATP / Automated Tests",
      target_url:  process.env.ATP_BASE_URL
        ? `${process.env.ATP_BASE_URL}#results`
        : undefined,
    }),
  }).catch(() => {});
}

/**
 * Post a detailed comment to the PR with full test results.
 */
export async function postPRComment(prEvent, { diffAnalysis, testResults, updatedTests, newTests, generatedFiles = [], atpPrUrl = null }, token) {
  if (!token) return;

  const passed  = testResults.filter(r => r.status === "pass").length;
  const failed  = testResults.filter(r => r.status !== "pass").length;
  const passRate = testResults.length ? Math.round(passed / testResults.length * 100) : 0;

  const riskEmoji = { critical:"🔴", high:"🟠", medium:"🟡", low:"🟢" };
  const statusEmoji = passRate === 100 ? "✅" : passRate >= 80 ? "⚠️" : "❌";

  const lines = [
    `## ${statusEmoji} ATP — Automated Test Results`,
    ``,
    `**PR:** #${prEvent.prNumber} ${prEvent.prTitle}`,
    `**Branch:** \`${prEvent.branchFrom}\` → \`${prEvent.branchTo}\``,
    `**Triggered by:** @${prEvent.author}`,
    ``,
    `### 📊 Results Summary`,
    `| Metric | Value |`,
    `|--------|-------|`,
    `| Pass Rate | ${passRate}% (${passed}/${testResults.length}) |`,
    `| Risk Level | ${riskEmoji[diffAnalysis.riskLevel] || "⚪"} ${diffAnalysis.riskLevel?.toUpperCase() || "UNKNOWN"} |`,
    `| Tests Run | ${testResults.length} |`,
    `| Tests Failed | ${failed} |`,
    `| Est. Test Time | ${diffAnalysis.estimatedTestTime || "—"} |`,
    ``,
    generatedFiles?.length ? [
      `### 🧪 ATP Generated Tests`,
      `ATP automatically wrote **${generatedFiles.length}** test file(s) for the changes in this PR.`,
      ...generatedFiles.map(f =>
        f.action === "created"
          ? `- ✅ **Created:** \`${f.fileName}\` — ${f.useCase?.title || "new test"}`
          : `- 🔄 **Updated:** \`${f.path}\` — ${f.reason || "updated for PR changes"}`
      ),
      atpPrUrl ? `\n**[View ATP's test PR →](${atpPrUrl})**` : "_Tests saved locally in ATP — connect a test repo in 🧪 Repos to enable auto-push._",
      ``,
    ].join("\n") : "",
    `### 🔍 AI Change Analysis`,
    `> ${diffAnalysis.summary}`,
    ``,
    `**Risk Reason:** ${diffAnalysis.riskReason || "—"}`,
    ``,
    diffAnalysis.affectedFeatures?.length ? [
      `**Affected Features:**`,
      ...diffAnalysis.affectedFeatures.map(f =>
        `- \`${f.feature}\` (${f.confidence} confidence) — ${f.reason}`
      ),
      ``,
    ].join("\n") : "",

    diffAnalysis.concerns?.length ? [
      `**⚠️ Concerns:**`,
      ...diffAnalysis.concerns.map(c => `- ${c}`),
      ``,
    ].join("\n") : "",

    `### 🧪 Test Results`,
    ...testResults.map(r => {
      const icon = r.status === "pass" ? "✅" : r.status === "error" ? "⚠️" : "❌";
      return `${icon} **${r.name}** — ${r.passed}/${r.total} assertions · ${r.duration ? `${(r.duration/1000).toFixed(1)}s` : ""}`;
    }),
    ``,

    updatedTests?.filter(t => t.updateStatus === "updated").length ? [
      `### 🔄 Updated Test Cases`,
      `The following tests were automatically updated based on code changes:`,
      ...updatedTests.filter(t => t.updateStatus === "updated").map(t =>
        `- \`${t.id}\` ${t.title}`
      ),
      ``,
    ].join("\n") : "",

    updatedTests?.filter(t => t.isBroken).length ? [
      `### 💔 Broken Tests`,
      `These tests may be broken by the changes:`,
      ...updatedTests.filter(t => t.isBroken).map(t =>
        `- \`${t.id}\` ${t.title} — ${t.brokenReason}`
      ),
      ``,
    ].join("\n") : "",

    newTests?.length ? [
      `### ➕ Suggested New Tests`,
      `Based on the changes, consider adding:`,
      ...newTests.map(t =>
        `- **${t.title}** (${t.priority}) — ${t.reason}`
      ),
      ``,
    ].join("\n") : "",

    `---`,
    `*Generated by [ATP](https://github.com/gracetshihatasics/atp) — Autonomous Test Platform*`,
  ].filter(Boolean).join("\n");

  // Find existing ATP comment to update instead of creating duplicates
  const commentsRes = await fetch(
    `${GH_API}/repos/${prEvent.repoFullName}/issues/${prEvent.prNumber}/comments`,
    { headers: { Authorization: `Bearer ${token}`, "User-Agent": "ATP-Bot" } }
  ).catch(() => null);

  let existingCommentId = null;
  if (commentsRes?.ok) {
    const comments = await commentsRes.json();
    const atpComment = comments.find(c =>
      c.user?.login === "github-actions[bot]" ||
      c.body?.includes("ATP — Automated Test Results")
    );
    if (atpComment) existingCommentId = atpComment.id;
  }

  const url    = existingCommentId
    ? `${GH_API}/repos/${prEvent.repoFullName}/issues/comments/${existingCommentId}`
    : `${GH_API}/repos/${prEvent.repoFullName}/issues/${prEvent.prNumber}/comments`;
  const method = existingCommentId ? "PATCH" : "POST";

  await fetch(url, {
    method,
    headers: {
      Authorization:  `Bearer ${token}`,
      Accept:         "application/vnd.github.v3+json",
      "Content-Type": "application/json",
      "User-Agent":   "ATP-Bot",
    },
    body: JSON.stringify({ body: lines }),
  }).catch(() => {});
}
